// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: campaign.proto
#ifndef GRPC_campaign_2eproto__INCLUDED
#define GRPC_campaign_2eproto__INCLUDED

#include "campaign.pb.h"

#include <grpc++/support/async_stream.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/proto_utils.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/status.h>
#include <grpc++/support/stub_options.h>
#include <grpc++/support/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace RTB5 {

}  // namespace RTB5


#endif  // GRPC_campaign_2eproto__INCLUDED
