// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: order.proto

#include "order.pb.h"
#include "order.grpc.pb.h"

#include <grpc++/channel.h>
#include <grpc++/impl/client_unary_call.h>
#include <grpc++/impl/rpc_service_method.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/async_stream.h>
#include <grpc++/support/sync_stream.h>
namespace RTB5 {

}  // namespace RTB5

